# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/usthe?useUnicode=true&characterEncoding=utf8
    username: root
    password: